# Generated by Django 5.0.1 on 2024-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
