# Generated by Django 5.0.1 on 2024-01-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_time', models.TimeField()),
                ('plane', models.CharField(max_length=24)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='cuy_app.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='cuy_app.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=20)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='cuy_app.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='Número de asiento', max_length=10, unique=True)),
                ('is_reserved', models.BooleanField(default=False, help_text='¿El asiento está reservado?')),
                ('passenger', models.ForeignKey(blank=True, help_text='Pasajero asignado al asiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='cuy_app.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Capacidad de pasajeros')),
                ('registration_number', models.CharField(help_text='Número de registro del avión', max_length=20, unique=True)),
                ('seats', models.ManyToManyField(blank=True, help_text='Asientos disponibles en el avión', related_name='planes', to='cuy_app.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=6, unique=True)),
                ('flight_destination_date', models.DateField(blank=True, null=True)),
                ('flight_arrival_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=45)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cuy_app.flight')),
                ('passengers', models.ManyToManyField(related_name='flight_tickets', to='cuy_app.passenger')),
            ],
        ),
    ]
